from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field



class ToolHumanReviewRequest(BaseModel):
    """ 
    Represents a request to involve a human operator 
    for a sensitive tool operation.
    """

    request: str = Field(
        ...,
        min_length=1,
        description="The original user request.",
    )

    reason: str = Field(
        ...,
        min_length=1,
        description="Why human intervention is required.",
    )

    operation: str | None = Field(
        default=None,
        description="Sensitive operation associated with the request.",
    )

    arguments: dict | None = Field(
        default=None,
        description="Arguments associated with the request.",
    )


class RAGHumanReviewRequest(BaseModel):
    """
    Represents a request to involve a human operator 
    when a RAG response requires review.
    """

    request: str = Field(
        ...,
        min_length=1,
        description="The original user request.",
    )

    reason: str = Field(
        ...,
        min_length=1,
        description="Why human intervention is required.",
    )

    confidence_score: float | None = Field(
        default=None,
        ge=0.0,
        lt=1.0,
        description="Confidence score that triggered human review.",
    )

    retrieved_documents: list[dict] = Field(
        ...,
        min_length=1,
        description="List of documents retrieved for the request.",
    )

    generated_answer: str | None = Field(
        default=None,
        description="Answer generated by the model for the request.",
    )


class HumanDecision(BaseModel):
    """
    Represents the decision made by the human operator.
    """

    decision: Literal["approve", "reject", "escalate"] = Field(
        ...,
        description="Decision made by the human operator.",
    )


    comment: str | None = Field(
        default=None,
        description="Optional comment provided by the human operator",
    )
